### ISSUE TITLE
Can't not run simple Test on linux (WSL, ubuntu) on net6.0

### ISSUE THREAD

**Issue by xjjius** [kazuyaujihara/build-rdkit#6]
Here is a simple test code which runs fine on net6.0 in windows.

```
static void Main(string[] args)
 { 
        var rwMol = RWMol.MolFromSmiles("C(Cl)(=O)CCC(=O)Cl");
        Console.WriteLine(RDKFuncs.calcAMW(rwMol));
}
```

However, when I publish it and run under WSL, I got this error:

Unhandled exception. System.TypeInitializationException: The type initializer for 'GraphMolWrap.RDKFuncsPINVOKE' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'SWIGExceptionHelper' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'RDKFuncs' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libRDKFuncs: cannot open shared object file: No such file or directory
   at GraphMolWrap.RDKFuncsPINVOKE.SWIGExceptionHelper.SWIGRegisterExceptionCallbacks_RDKFuncs(ExceptionDelegate applicationDelegate, ExceptionDelegate arithmeticDelegate, ExceptionDelegate divideByZeroDelegate, ExceptionDelegate indexOutOfRangeDelegate, ExceptionDelegate invalidCastDelegate, ExceptionDelegate invalidOperationDelegate, ExceptionDelegate ioDelegate, ExceptionDelegate nullReferenceDelegate, ExceptionDelegate outOfMemoryDelegate, ExceptionDelegate overflowDelegate, ExceptionDelegate systemExceptionDelegate)
   at GraphMolWrap.RDKFuncsPINVOKE.SWIGExceptionHelper..cctor()
   --- End of inner exception stack trace ---
   at GraphMolWrap.RDKFuncsPINVOKE.SWIGExceptionHelper..ctor()
   at GraphMolWrap.RDKFuncsPINVOKE..cctor()
   --- End of inner exception stack trace ---
   at GraphMolWrap.RDKFuncsPINVOKE.RWMol_MolFromSmiles__SWIG_3(String jarg1)
   at GraphMolWrap.RWMol.MolFromSmiles(String smi)
   at Test.Program.Main(String[] args) in D:\Project\Test\Test\Program.cs:line 45

It looks like WSL missed some deps. I have found RDKFuncs.so in the runtimes/linux-x64/native folder, so it may be one of it deps missing.

Could you please look into this issue? @kazuyaujihara 

Your help will be greatly appreciated!

**Comment by k-ujihara** [comment]
It may need to add something to `LD_LIBRARY_PATH` like this.
```
export LD_LIBRARY_PATH=$PWD/bin/Release/net5.0/runtimes/linux-x64/native
```

**Comment by k-ujihara** [comment]
This is fixed in this [release](https://github.com/kazuyaujihara/build-rdkit/issues/5).

**Comment by xjjius** [comment]
@kazuyaujihara Yes! I have tested and it works under WSL !!!  Thanks again for your work!!!
